---

- name: List modules
  shell: 'metricbeat modules list'
  args:
    chdir: '/etc/metricbeat/modules.d'
  register: modules_list
  changed_when: false

- debug:
    var: modules_list

- name: Enable metricbeat modules
  shell: 'metricbeat modules enable {{ item }}'
  args:
    chdir: '/etc/metricbeat'
    # creates: '/etc/metricbeat/modules.d/{{ item }}.yml'
  with_items: '{{ metricbeat_modules }}'
  when: item not in (modules_list.stdout.split("Disabled:")[0])
