---

- name: Install metricbeat
  apt:
    name: metricbeat
    state: present

- name: Metricbeat configuration
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  with_items:
    - '{{ _metricbeat_configs }}'
  notify: restart metricbeat
