---

- name: Enable filebeat modules
  shell: 'filebeat modules enable {{ item }}'
  args:
    chdir: '/etc/filebeat'
  creates: '/etc/filebeat/modules.d/{{ item }}.yml'
  with_items: '{{ filebeat_modules }}'
